image: python:3.11-bullseye

stages:
  - Static Code Analysis
  - Test
  - Deploy

flake8:
  stage: Static Code Analysis
  image: python:${PYTHON_VERSION}-bullseye
  allow_failure: true
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.9", "3.10", "3.11"]
  script:
    - pip install flake8 genbadge[flake8] pytest pytest-cov
    - mkdir ./flake8
    - flake8 toolboks/ --exit-zero --statistics --tee --output-file ./flake8/flake8stats.txt
    - genbadge flake8 -i ./flake8/flake8stats.txt -o ./flake8/flake8.svg
  artifacts:
    paths:
      - ./flake8/

pylint:
  stage: Static Code Analysis
  image: python:${PYTHON_VERSION}-bullseye
  allow_failure: true
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.9", "3.10", "3.11"]
  script:
    - pip install pylint pylint-exit anybadge pytest pytest-cov
    - mkdir ./pylint
    - pylint --output-format=text toolboks/ | tee ./pylint/pylint.log || pylint-exit $?
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - anybadge --label=pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 8=bright_red 9=yellow 10=green
  artifacts:
    paths:
      - ./pylint/

pytest:
  stage: Test
  image: python:${PYTHON_VERSION}-bullseye
  allow_failure: false
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.9", "3.10", "3.11"]
  script:
    - pip install pytest genbadge[tests]
    - mkdir ./pytest
    - python -m pytest . --junitxml=pytest/test_report.xml
    - genbadge tests -i ./pytest/test_report.xml -o ./pytest/pytest.svg
  artifacts:
    paths:
      - ./pytest/
    reports:
      junit: ./pytest/test_report.xml

coverage:
  stage: Test
  script:
    - pip install pytest pytest-cov
    - coverage run -m pytest
    - coverage report
    - coverage xml -o coverage/coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - ./coverage/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./coverage/coverage.xml